jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -6,20 +6,27 @@ pipeline {
                 git branch: 'main', url: 'https://github.com/MohamedSbika/Mern_app_Docker_Copie.git'
             }
         }
-        // stage('Install Docker Compose') {
-        //     steps {
-        //         script {
-        //             sh '''
-        //             if ! command -v docker-compose &> /dev/null; then
-        //                 echo "Docker Compose not found, installing..."
-        //                 sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-        //                 sudo chmod +x /usr/local/bin/docker-compose
-        //             fi
-        //             docker-compose --version
-        //             '''
-        //         }
-        //     }
-        // }
+        stage('Install Docker Compose') {
+            steps {
+                script {
+                    sh '''
+                    if ! command -v docker-compose &> /dev/null; then
+                        echo "Docker Compose not found, installing..."
+                        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+                        sudo chmod +x /usr/local/bin/docker-compose
+                    fi
+                    docker-compose --version
+                    '''
+                }
+            }
+        }
+                stage('Build Images') {
+            steps {
+                script {
+                    sh '/usr/local/bin/docker-compose build'
+                }
+            }
+        }
         // stage('Tag Images') {
         //     steps {
         //         script {
